package red.client.config;

import dev.isxander.yacl3.api.Binding;
import dev.isxander.yacl3.api.ConfigCategory;
import dev.isxander.yacl3.api.Option;
import dev.isxander.yacl3.api.OptionDescription;
import dev.isxander.yacl3.api.YetAnotherConfigLib;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.FloatSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;
import red.client.flarecombat.config.FlareConfig;
import red.client.fishing.config.BezalFarmerConfig;
import red.client.fishing.config.CinderbatHighlightConfig;
import red.client.fishing.config.FishConfig;
import red.client.fishing.config.SpikeHelperConfig;
import red.client.fishing.config.XYZConfig;
import red.client.scheduler.MacroSchedulerConfig;

public final class RedClientYaclConfigScreen {
    private RedClientYaclConfigScreen() {
    }

    public static Screen create(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Text.literal("RedClient Settings"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Fishing"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Sea Creature Killer"))
                                .description(desc("Automatically fights detected sea creatures while fishing."))
                                .binding(Binding.generic(false, FishConfig::isSeaCreatureKillerEnabled, FishConfig::setSeaCreatureKillerEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Recast Delay (ticks)"))
                                .description(desc("Delay before re-casting after a catch. 20 ticks = 1 second."))
                                .binding(Binding.generic(10, FishConfig::getRecastDelay, FishConfig::setRecastDelay))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(0, 50)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " ticks")))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Reeling Delay (ticks)"))
                                .description(desc("Delay before reeling in after bite detection."))
                                .binding(Binding.generic(6, FishConfig::getReelingDelay, FishConfig::setReelingDelay))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(0, 15)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " ticks")))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Group Kill Threshold"))
                                .description(desc("How many sea creatures to wait for before attacking."))
                                .binding(Binding.generic(1, FishConfig::getSeaCreatureKillThreshold, FishConfig::setSeaCreatureKillThreshold))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 30)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + (value == 1 ? " creature" : " creatures"))))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hyperion Look Down"))
                                .description(desc("Looks down while casting Hyperion for more reliable ground hits."))
                                .binding(Binding.generic(true, FishConfig::isHyperionLookDownEnabled, FishConfig::setHyperionLookDownEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Ungrab Mouse"))
                                .description(desc("Unlocks cursor while macro is active so you can alt-tab."))
                                .binding(Binding.generic(false, FishConfig::isUngrabMouseEnabled, FishConfig::setUngrabMouseEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Hunting"))
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Flare Combat Mode (1=Hyperion, 2=Fire Veil)"))
                                .description(desc("Choose weapon loop mode for Flare combat."))
                                .binding(Binding.generic(1, FlareConfig::getCombatMode, FlareConfig::setCombatMode))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 2)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value == 1 ? "1 - Hyperion" : "2 - Fire Veil Wand")))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Flare Click Count"))
                                .description(desc("Number of right-clicks per attack cycle."))
                                .binding(Binding.generic(3, FlareConfig::getClickCount, FlareConfig::setClickCount))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 10)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " clicks")))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Bezal Farmer"))
                                .description(desc("Enables Bezal farming automation and target tracking."))
                                .binding(Binding.generic(false, BezalFarmerConfig::isEnabled, BezalFarmerConfig::setEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Bezal Auto Aim"))
                                .description(desc("Automatically rotates aim toward the tracked Bezal."))
                                .binding(Binding.generic(true, BezalFarmerConfig::isAutoAimEnabled, BezalFarmerConfig::setAutoAimEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Text.literal("Bezal Attack Distance"))
                                .description(desc("Attack only when Bezal is within this distance."))
                                .binding(Binding.generic(3.0f, () -> (float) BezalFarmerConfig.getAttackDistance(), value -> BezalFarmerConfig.setAttackDistance(value.doubleValue())))
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .range(1.0f, 10.0f)
                                        .step(0.1f)
                                        .valueFormatter(value -> Text.literal(String.format("%.1f blocks", value))))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Bezal Click Count"))
                                .description(desc("Number of clicks performed during Bezal attack bursts."))
                                .binding(Binding.generic(3, BezalFarmerConfig::getClickCount, BezalFarmerConfig::setClickCount))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 10)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " clicks")))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Bezal Blackhole"))
                                .description(desc("Use blackhole support when available."))
                                .binding(Binding.generic(false, BezalFarmerConfig::isBlackholeEnabled, BezalFarmerConfig::setBlackholeEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("XYZ Macro"))
                                .description(desc("Enable XYZ movement/targeting macro."))
                                .binding(Binding.generic(false, XYZConfig::isEnabled, XYZConfig::setEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Text.literal("XYZ Search Range"))
                                .description(desc("Maximum range used to search for XYZ targets."))
                                .binding(Binding.generic(30.0f, () -> (float) XYZConfig.getSearchRange(), value -> XYZConfig.setSearchRange(value.doubleValue())))
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .range(5.0f, 100.0f)
                                        .step(1.0f)
                                        .valueFormatter(value -> Text.literal(String.format("%.0f blocks", value))))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Cinderbat Highlight"))
                                .description(desc("Highlights detected cinderbats through walls."))
                                .binding(Binding.generic(true, CinderbatHighlightConfig::isEnabled, CinderbatHighlightConfig::setEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Text.literal("Cinderbat Detection Range"))
                                .description(desc("How far to scan for cinderbats around your player."))
                                .binding(Binding.generic(220.0f, () -> (float) CinderbatHighlightConfig.getDetectionRange(), value -> CinderbatHighlightConfig.setDetectionRange(value.doubleValue())))
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .range(20.0f, 500.0f)
                                        .step(5.0f)
                                        .valueFormatter(value -> Text.literal(String.format("%.0f blocks", value))))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Cinderbat Debug"))
                                .description(desc("Shows scan and match diagnostics in chat."))
                                .binding(Binding.generic(false, CinderbatHighlightConfig::isDebugEnabled, CinderbatHighlightConfig::setDebugEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Spike Helper"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Enabled"))
                                .description(desc("Enable Spike helper targeting and tracking."))
                                .binding(Binding.generic(false, SpikeHelperConfig::isEnabled, SpikeHelperConfig::setEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Highlight"))
                                .description(desc("Draw Spike highlight when a valid target is found."))
                                .binding(Binding.generic(true, SpikeHelperConfig::isHighlightEnabled, SpikeHelperConfig::setHighlightEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Aim Assist"))
                                .description(desc("Automatically adjust aim toward the tracked Spike."))
                                .binding(Binding.generic(false, SpikeHelperConfig::isAimAssistEnabled, SpikeHelperConfig::setAimAssistEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Scheduler"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Breaks Enabled"))
                                .description(desc("Enable timed run/break scheduler cycle."))
                                .binding(Binding.generic(false, MacroSchedulerConfig::isBreakEnabled, MacroSchedulerConfig::setBreakEnabled))
                                .controller(BooleanControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Run Time (minutes)"))
                                .description(desc("How long macros run before taking a break."))
                                .binding(Binding.generic(60, MacroSchedulerConfig::getRunTime, MacroSchedulerConfig::setRunTime))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 180)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " min")))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Break Min (minutes)"))
                                .description(desc("Minimum break duration."))
                                .binding(Binding.generic(1, MacroSchedulerConfig::getBreakMinTime, MacroSchedulerConfig::setBreakMinTime))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 60)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " min")))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Break Max (minutes)"))
                                .description(desc("Maximum break duration."))
                                .binding(Binding.generic(25, MacroSchedulerConfig::getBreakMaxTime, MacroSchedulerConfig::setBreakMaxTime))
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(1, 60)
                                        .step(1)
                                        .valueFormatter(value -> Text.literal(value + " min")))
                                .build())
                        .build())
                .save(() -> {
                    FishConfig.save();
                    FlareConfig.save();
                    SpikeHelperConfig.save();
                    BezalFarmerConfig.save();
                    XYZConfig.save();
                    CinderbatHighlightConfig.save();
                    MacroSchedulerConfig.save();
                })
                .build()
                .generateScreen(parent);
    }

    private static OptionDescription desc(String text) {
        return OptionDescription.of(Text.literal(text));
    }
}
